groups:
- name: AllInstances
  rules:
  - alert: InstanceDown
    # Condition for alerting
    expr: up == 0
    for: 5m
    # Annotation - additional informational labels to store more information
    annotations:
      title: 'Instance {{ $labels.instance }}{{ $labels.job }} or Node exporter down'
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
    # Labels - additional labels to be attached to the alert
    labels:
      severity: 'critical'

